  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Painters"
  weight = 200
  identifier = "painters"
  url = "/painters/"
  
  [[main]]
  name = "Hackers"
  weight = 300
  identifier = "hackers"
  url = "/hackers/"
  
   [[main]]
  name = "Iris"
  weight = 400
  identifier = "iris"
  url = "/iris/"
  
   [[main]]
  name = "about"
  weight = 500
  identifier = "about"
  url = "/about/"
  
  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
