  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "云门 & Painters"
  weight = 200
  identifier = "painters"
  url = "/painters/"
  
  
  [[main]]
  name = "兰台 & Hackers"
  weight = 300
  identifier = "hackers"
  url = "/hackers/"


  [[main]]
  name = "en blog"
  weight = 400
  identifier = "en blog"
  url = "/enblog/"
  
   [[main]]
  name = "about"
  weight = 500
  identifier = "about"
  url = "/about/"
  
  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
