
title = "I'm magisk"
author = "magisk"
#copyright = "2022-2023"
description = "Dropped into Catch-22."
profilePicture = "images/profilezzz.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["painters"]
#images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/your-form-hash-here"
contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = false # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.



[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/magiskxzy"

[[socialIcons]]
icon = "fab fa-telegram"
title = "Telegram"
url = "https://t.me/magisk_xzy"

[[socialIcons]]
icon = "fab fa-steam"
title = "Steam"
url = "https://steamcommunity.com/profiles/76561199093840652"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/chenyuan9"

[[socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:894473271xzy@gmail.com"


[mermaid]
enable = true

[params]
  enableGitalk = true

[params.gitalk] 
    clientID = "[6c271540221e5fff0847]" # Your client ID
    clientSecret = "[ ee0b9ff755da90afd26f6bcc7fb93822304ae9fd]" # Your client secret
    repo = "magiskxzy.cc" # The repo to store comments
    owner = "chenyuan9" # Your GitHub ID
    admin= "chenyuan9" # Required. GitHub repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # GitHub issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a GitHub issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

