---
title: "悉达多寻找悉达多"
output: html_document
date: "2025-01-01"
---


## 旅行
24年旅行的第一站是北京，为的是不错过杉本博司在中国的艺术展——《无尽的刹那》。我于端午假期的第一天从武汉飞往北京见朋友，第二天的第一站便是去往798艺术区。抵达的当晚，我和朋友漫步在宾馆外的大道上聊着许多有关政治的禁忌话题，一场运动事起事落，三十多年后的如今似乎只剩下些人假借民主干着诈骗的勾当...来到《无尽的刹那》的展馆，也是比较幸运的获得了前50名进入场馆的纪念棱镜。总体参观下来，我觉得杉本博司是一个很天才、很有想法的人，用显影液在废弃的相纸上写成的《心经》、用一场电影的时长曝光拍摄剧院、用黑白胶卷拍摄的《肖像》更是栩栩如生（杉本博司用黑白抹去了蜡像在一般光线下的失真表现）还有如今仍挂在我床头的那副千年不变的海景，当然还有《放电场》、《千佛寺》之类的作品。只是，这样的作品对我来说太素了，如今的我不论主观还是客观都无法做到“照见五蕴皆空”的。再后来，我们吃过饭就启程前往什刹海，小时候就听闻过很多什刹海的故事呢，冬收夏用的冰块、纳兰性德云云。但最让我觉得有趣的，并非在6月什刹海上泛舟晒太阳，而是操着一口纯正北京话的大爷在公交上的聊天，仿佛北京人天生都具有那种聊天的天分和幽默的细胞，虽然不大记得大爷的聊天内容，却是坐在大爷后面听着聊天傻乐。那时，公交上来另一位大爷，不付车钱的往里闯，还叫嚣着自己曾经规划过北京市公交的许多线路，因此司机不应当找他要车钱和老年卡，怪有意思的哈哈哈。再后来呀，一直聊天的大爷聊到了胡耀邦，我们是在那时候下的车。泛舟什刹海之后，时间还挺早，我和朋友租借了共享单车便开始无目的的闲逛，顺着什刹海的前海、后海一路骑到了北海公园，我们并不打算进去。于是往左，拐进了地安门大街，一路跟着前面一个应许是本地的小男孩，从景山西街骑到了北长街。至此似乎已经能看到天龙人的居所了，很早便听说中南海有着苏州园林的绝顶之作，只是没想到映入眼帘的是在城墙上晒衣服被子的人。继续往前，那是南长街和北长街，大概一公里的路程中，我见到了此生见过最多的兵力，十步一岗，我的心里只剩恐惧，根本不敢抬头。赶紧往前，夕阳日落的阳光照到了人民大会堂的西侧，西侧那宛如罗马万神殿的大柱在金灿灿的阳光下照到我在我的心中，一时失语，回过神来脑海里蹦出“伟大”两个字。往前吧，累了便在前门那里买上一盒驴打滚和艾窝窝充饥准备返程，等公交的时候，遇到了一群异鸟在天空飞旋，一圈又一圈...

年假去的是随州的朋友家里，但是