---
title: "不灭恶龙与英雄登场"
author: "magisk"
date: "2023-11-15"
output: html_document
---

很久很久以前，在某个僻远的村庄里人们安静而淳朴的生活着，突然某一天恶龙袭来、遮天蔽日，打破了一切宁静......咳咳咳，虽然我很想同博尔赫斯和卡夫卡先生那样讲述一个引人入胜的故事，奈何才气无几，对文字更是没有那般驾轻就熟的功底，因此只好平铺直叙了。

对于是非善恶的讨论一直都是影视作品有意无意触及的主题，而成长的经历让我很难再去相信"好人"、"坏人"这种单一、片面的分类方式，很遗憾的是身边的影视作品同样历经二十余年似乎并没有什么大的改变和进步，仍然是一个又一个纸片式故事中的正义主角、坏蛋反派。越来越感觉食之无味的我也逐渐不再看电视剧，觉得有着更丰富题材、市场更加广阔、讨论问题更加切近的电影才值得花时间观赏。但当我的视角逐渐变广，便开始意识到事实并非如此：《Yes,Minister》和《Yes,Prime Minister》是我最先看到并让我极为震撼的电视剧，此前我从未看过能用如此生动、有趣的方式将故事呈现出来的剧，并且整个故事毫无架子、没有英雄，没有一丝一毫想要打着电视剧的幌子来"教育"观众的意思，却最终达到了将"政治"这一主题诠释得非常具体的目的，以致于其中的某些经典对白不仅仅适用于1980年代的英国，甚至在当今每个国家在处理事件中都能找到对应的场景。但谈论政治本身在我们国家就极为敏感，而最近看到的《绝命毒师》更是如此，作为一部讲述大毒枭的电视剧，在最终的结尾主角怀特老师用自己的方式给故事画上了一个句号：将所有穷凶极恶之徒全部杀死，警察到来之前怀特老师在生命倒数的时刻走进了制毒实验室里，却放走了与自己有着千丝万缕联系的小粉。或许那一刻不应该叫他怀特老师，应该叫他"海森堡"，这位海森堡同希特勒一样，罪行无数却未经审判的去世了。有人曾经说过，希特勒未经审判而自杀，直接导致了在希特勒死后的今天仍有着一群希特勒的信徒，不成势力也成问题。我不敢想这样一位名叫海森堡的大毒枭，杀人之后会用氢氟酸毁尸灭迹、逼迫妻子为自己洗钱、制造的毒品帝国空前绝后、罪行数不胜数的海森堡居然在临死之前还用他自己的方式实现了一次"正义"。这样的故事会带来多少的不稳定因素我不太好说，但在统治者、尤其是独裁者眼中出现隐患等同于出现问题，因此这样的故事能够播出，甚至由于故事的精彩性和创作的艺术性而广受追捧让我感到的震撼，不亚于当年我第一次看到反马克思主义演讲。

而不止于《绝命毒师》，《汉尼拔》的主角钟爱吃人；《纸牌屋》的主角为了总统之位暗杀背叛者、为消除异端者明争暗斗；《风骚律师》的主角利用法律漏洞帮助各类罪犯脱罪......我很奇怪，为什么？为什么美剧的主角全是坏人？难道，英雄已死，恶龙登场？

我想，对于影视题材的探索和挖掘一直都是人们正在做的事情，而虽然英雄登场这类的桥段仍然在荧幕中出现、在大众里有市场，但新意已不再，于是编剧的改进中，这类的英雄不再普通、拥有超能，这样的电影也以特效与超能为卖点。而不同于前者，另一类的编剧则更青睐于打磨剧本的深度而非广度--挖掘内心。正所谓"追索到人心的深处，却看到人心的浅薄"，挖掘内心无异于将"英雄"拉下神坛，因为再怎么称呼他们英雄、伟人、领袖、精英，他们也不过是一个普通人。于是