---
title: "此时此地"
author: "magisk"
date: "2024-04-06"
output: html_document
---

杂乱无章的躺在门口的三个铁质皱纸团、一个被切去面部的金属头、一个禁止符号，这些摆在门口的物件无不吸引着我进入这座美术馆，理由很充分了，但还不必要。但很快上天便将这个必要条件送到了我面前 -- 是一个"过度拟合"的艺术展名字，梢上这是加班又无任务的一天。

我做决定向来很快，早上的想法，中午午休便出发了。我很快便看完了一楼，因为一楼在装修，只剩一些清明假期未开门的咖啡店招徕客人的书架里的书，品类都对我没有什么吸引力。楼梯间的路标上写着"二楼"、"过度拟合"，我赶上二楼，看完了一则序和一则跋，看到的却是把树莓派放进画框里、把矿石放到显微镜下的作品，我理解作者想要用这些理工科的代表物代表时代的发展，但我实在想不出这些和"过度拟合"的主题有什么联系，尤其是"过度"两字。继续往上，第三层的展品看完之后我有些不适感。并非在作品中出现了裸体、血腥，而是三层的作品仿佛都是在恶搞，在我的感觉里第三层的"未来"跟宇航员是必然挂钩的，几乎每幅作品都会有宇航员这个意象，而为了表达新意，于是便将宇航员进行各种杂糅，但在我看来只是创造力贫瘠的表现，各种怪异动作的强行附加让我没有觉得这是一件艺术品，而是恶搞，并且我也不认为这属于解构。或许只是我固执的认为恶搞不同于解构，但三楼的展品，我并不喜欢。

就在已有去意的时候发现还有负一楼，来都来了，也就抱着无所谓的态度去转一转吧。"呼吸"是我在那里最先记住的词语，推荐序的作者是和"过度拟合"推荐者是同一人，文笔一般。这层的展品用三个短片征服了我，尤其是第三支影片临近结束时那段酷似卓别林的定格，我可以很确定，导演在讨论很现实的问题，有关女性主义、有关每一个劳动者的权益。导演仿佛在用那不断变化的形体和脸部强调，影片的主角可以是每一个人，我们不要逃避，也无法逃避。三支影片在三个放映室，这之间的距离放了很多这导演的摄影作品，拍的极好，色彩舒适，主体明确，是我在此时、此地可以感同身受的作品。临走前，我记住了作者的名字，他叫侯帅。



后来啊，我也在想，曾几何时我也是一个疯狂热爱浪漫主义的人，那些天马行空的、不沾烟火的也是我曾喜欢的。念着"自信人生两百年、会当击水三千里"、"春来我不先开口，哪个虫儿敢作声"热血澎湃，






















