---
title: "十年才一觉，东华梦，依旧五云高"
author: "magisky"
date: "2023-04-16"
output: html_document
tags: 
  -毕业
---

### This is the dedication part of my graduation thesis. 

<!--more-->



## 毕业论文致谢   

我的本科生涯到这里就差不多结束了。   

如江淹在《别赋》中所言：“黯然销魂者，唯别而已矣”。离别之际，难免黯然，春秋代序，弹指顷四年。   

四年前，我怀着对世界的期待、对知识的向往与对浪漫的等待走进大学的校园中，在突破了很多的限制之后，见识到了无数前辈们为之奋斗终身的愿景。这愿景，是莱布尼兹“我们的宇宙，在某种意义上是上帝所创造的最好的一个”的乐观；是洛必达公爵为“洛必达法则”付钱的故事；是高木贞治在证明克罗内克青春之梦猜想之后所带来的日本数学的大繁荣；是历经两百余年一个个数学家不断完善现代微积分与分析学的现代逻辑；亦或是GNU、Linux和开源社区为人们创造出来的许许多多的免费项目供全球同好学习使用。在这片愿景中我于是明白霍金在《时间简史》中提到“纯粹理性批判”的意义，我于是变成了“科学”这一宗教的虔诚信徒，这份虔诚让我走进了统计系。   

但我是个亚伯拉罕式的信徒，如果天主教足够糜烂而不倒，那我的信仰自然也可以追随天主。拉普拉斯曾认真的研究过明天的太阳能否升起，作为一个现代生活的学生确实有些难以理解，太阳的运行规律在物理学界明明已经证实，为什么最后计算的概率居然还是99.9997%？我们“统计”既然不能像物理那样由内向外的了解规律，那凭什么被称为科学，这样的研究似乎也没有长远的意义。但无论是Alpha Go，深蓝，还是如今的chatGPT，一波又一波的浪潮背后，机器学习的原理似乎并有没太大更改。但，上帝是否存在呢？人们仍然无从回答。所以我仍然会信仰统计，哪怕Judea Pearl批判如今的机器学习其本质更像是曲线拟合。并且我会像哈代为数学家做的辩白那样，也为统计做一些简短的辩白：在上帝未知、物理难解的时候，概率与统计将会是我们与命运在赌桌上的底牌。   

我知道，物理学家们的八卦时间中也不会仍然讨论夸克，正常人需要浪漫。如果你不曾拥有诗歌、王位与太阳，不能终日徜徉在茂密芬芳的山林撷取种种野趣，或许你可以骑上仓央嘉措的白鹿在狄金森的想象草原上远山拾梦，而塞莱特的歌将是你献给月亮的小夜曲。如果，生活确实欺骗了你，我希望可以送你一句祝福。   

在大学，我们谈论人文与人本，虚无与存在，科学与哲学。   
	
我之所学，以人为本，宇宙次之，其他同理。   

最后的最后，谢谢郭一帆，我从小玩到大的朋友，在他的帮助下我看到更多的文献资料，为我的论文撰写提供了莫大的帮助。谢谢生命，谢谢我的家人，谢谢这一路所有遇见的前辈、朋友，谢谢这片饱经苦难的土地，谢谢这么美的文字。



