---
title: "论文复现『soft-DTW：a Differentiable Loss Function for Time-Series』"
author: "magisk"
date: "2023-07-20"
output: md_document
---

[soft-DTW：a Differentiable Loss Function for Time-Series](https://arxiv.org/pdf/1703.01541v2.pdf)原文下载

## 翻译

### 摘要：

我们在本文提出一种基于著名的动态时间规整(DTW)差异的可微学习损失函数，用于比较时间序列数据之间的差异。与欧氏距离不同，DTW可以比较具有不同长度的时间序列，并且对于时间维度上的平移或拉伸具有鲁棒性。为了计算DTW,一种常规方法是使用动态规划解决两个时间序列之间的最小成本校准。我们的工作利用了DTW的一种平滑形式，称为soft-DTW，它计算所有校准成本的soft最小值。我们在这篇论文中展示了soft-DTW是一个可微的损失函数，而且它的值和梯度都可以以二次时间/空间复杂度计算（而DTW具有二次时间复杂度但线性空间复杂度）。我们展示了这种正则化特别适用于在DTW几何空间下对时间序列进行平均化和聚类的任务，在这个任务中，我们的方法明显优于现有的基准方法。接下来，我们建议通过以soft-DTW的方式最小化输出时间序列机器与地面真实标签之间的拟合来调整其参数。

### 1.介绍

监督学习的目标是通过使用输入与输出对象的示例，学习将输入映射到输出的关系。当输出对象具有结构时，例如它们不是向量，这个任务明显更加困难。我们在这里研究每个输出对象都是时间序列的情况，即一系列随时间索引的观测值。虽然将时间视为另一个特征，并将向量时间序列处理为所有这些向量的串联是很诱人的，但采用这种简单的方法会导致几个实际问题：时间索引的现象通常在时间轴上的某些区域被拉伸（例如，以稍慢于平常的速度发出的单词），但其特征不受影响；不同的采样条件可能导致它们具有不同的长度；时间序列可能不同步。

**DTW模型** 用于时间序列的生成模型通常在考虑上述不变性的基础上构建：这些属性通常通过潜在变量和/或马尔可夫假设来处理。一种受到几何学启发的更简单的方法，是通过直接定义时间序列之间的差异来实现这些不变性，例如DTW score。DTW计算两个时间序列之间的最佳对齐（最优对齐本身也可能是感兴趣的），这两个时间序列的长度分别为n和m。首先，通过计算这些点之间的$n×m$成对距离矩阵，然后使用Bellman递推法进行动态规划（DP），其计算成本为二次复杂度（nm）。动态时间规整（DTW）的几何性质。由于DTW有效地编码了一类有用的不变性，它经常被用于判别性框架中（例如，使用k-NN或SVM分类器），以预测实数或类别标签的输出，并在该背景下进行了优化以提高运行速度。

**DTW的几何性质** 由于DTW有效地编码了一类有用的不变性，它经常被用于判别性框架中（例如，使用k-NN或SVM分类器），以预测实数或类别标签的输出，并在该背景下进行了优化以提高运行速度。最近Petitjean等人在2011年的研究和Petitjean同Ganc¸arski在2012年的研究表明，DTW可以用于更具创新性的任务，例如使用DTW差异进行时间序列平均化。更普遍地说，将时间序列的中心合成为一个整体可以被视为使用DTW作为拟合损失输出整个时间序列的首次尝试。然而，从计算角度来看，这些方法受到DTW不可微分且在优化过程中不稳定的影响。

**Soft-DTW** 与这些发展平行的是，一些作者考虑使用Bellman的递归的平滑修改来定义平滑的DP距离或核函数。当应用于DTW差异时，这种正则化导致了soft-DTW得分，它考虑了两个时间序列之间所有可能对齐所涵盖的所有成本的软最小值。尽管考虑了所有对齐而不仅仅是最优对齐，但soft-DTW可以通过对Bellman递归进行轻微修改来计算，在这种修改中，所有的(min, +)运算被替换为(+, ×) 运算。因此，无论是DTW还是soft-DTW，都具有相对于序列长度的时间复杂度为二次的特点，而空间复杂度为线性。由于soft-DTW可以与核机器一起使用，在分类任务中使用soft-DTW相对于DTW通常会观察到性能的提升。

**我们的贡献** 


在本论文中，我们探索了平滑动态时间规整（DTW）的另一个重要优势：与原始的DTW差异不同，soft-DTW在所有参数上都是可微分的。我们展示了soft-DTW相对于其所有变量的梯度可以作为计算差异本身的副产品得到，但会增加二次存储成本。我们利用这一事实提出了一种替代方法来处理（Petitjean等人，2011年）提出的DTW质心聚类算法（DBA），并观察到我们的平滑方法在该任务中明显优于已知的基准方法。更一般地说，我们建议使用soft-DTW作为拟合项来比较合成时间序列片段的机器输出与地面真实观测的差异，就像例如，正则化的Wasserstein距离用于计算质心（Cuturi＆Doucet，2014年），后来用于拟合输出直方图的判别器（Zhang等人，2015年；Rolet等人，2016年）一样。当与灵活的学习架构（如神经网络）配对时，soft-DTW允许进行可微的端到端方法，用于设计时间序列的预测和生成模型，如图1所示。在我们提出的方法中，soft-DTW作为一个拟合项，可以用于将合成的时间序列片段与地面真实观测进行比较，从而设计预测和生成时间序列的机器学习模型。在使用灵活的学习架构（如神经网络）时，soft-DTW允许实现端到端的可微分学习方法。这种方法可以应用于多种时间序列相关的任务，如分类、聚类等。我们的实验结果表明，使用soft-DTW可以在一些任务中明显提高性能，超过了传统的DTW方法。

























